pytorch/ossci-job-dsl

- src/main/groovy/ossci/caffe2/Images.groovy
Need to merge this to get the new deb docker images generated and then merge #4 to start using them
> Add rocmdeb docker images

- src/jobs/caffe2.groovy
- src/jobs/packages.groovy
Making a PR to make it easier to see my changes
> Moving package jobs to separate file

- src/jobs/pytorch.groovy
Skips building PyTorch locally and instead installs a nightly CUDA 8.0 build.
> Skips building PyTorch and instead installs a nightly

- src/jobs/pytorch.groovy
Will push to the `gh-pages` branch for tutorials as a precursor to merging into `master` branch.
> Push from `rc1` to `gh-pages`

- src/jobs/pytorch.groovy
> push docs to origin/site rather than origin/master

- src/jobs/horizon.groovy
- src/main/groovy/ossci/horizon/Users.groovy
pytorchbot can't update facebookresearch
> Use caffe2bot for Horizon

- src/jobs/pytorch.groovy
Switching the branch in tutorial build scripts.
> Change pytorch tutorials build script after rc1 -> master merge.

- src/jobs/pytorch.groovy
Ref: https://github.com/pytorch/pytorch/issues/13951
> Make built docs have https to pytorch site

- src/main/groovy/ossci/caffe2/Images.groovy
> [llvm8] Add llvm image.

- src/main/groovy/ossci/caffe2/Images.groovy
Add job for build clang with assertions on
> Add clang debug job

- src/jobs/pytorch_docker.groovy
See https://github.com/pietern/pytorch-dockerfiles/pull/32
> Move trusty images to xenial

- src/jobs/pytorch_docker.groovy
See https://github.com/pytorch/pytorch/pull/24814
> Add xenial py3.6 clang7 config

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
> upgrade caffe2 docker deployed version to 315

- src/main/groovy/ossci/caffe2/Images.groovy
> Bring ONNX used docker back

- src/jobs/pytorch.groovy
CC @ezyang @xw285cornell @sunway513
> set numParallelTests = 3 to create test3

- README.md
https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-ecr-get-login
> AWS CLI v2 change

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> bump dockerversion

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Docker hash taken from https://app.circleci.com/pipelines/github/pytorch/pytorch/236259/workflows/e98ed9e4-bbbe-4953-8c35-595841590319/jobs/8762364
> updating docker hash for rocm build and test

- src/jobs/pytorch.groovy
- src/main/groovy/ossci/caffe2/Images.groovy
Reverts pytorch/ossci-job-dsl#84
> Revert "upgrade rocm image to 3.9"

- src/jobs/caffe2.groovy
- src/jobs/pytorch.groovy
- src/main/groovy/ossci/GitUtil.groovy
Reverts pytorch/ossci-job-dsl#81
> Revert "generate DOCKER_IMAGE_TAG based on git rev-parse"

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Reverts pytorch/ossci-job-dsl#91
> Revert "update ROCm CI image tag to latest, to pick up hipMAGMA support"

- src/jobs/pytorch.groovy
trying to improve ROCm CI throughput
> remove nightly caffe2 debug job

- src/jobs/pytorch.groovy
adds enablePytorch and enableCaffe2 options to master jobs
> disable caffe2 jobs on master commits

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Uses docker image built in https://github.com/pytorch/pytorch/pull/56448
cc @jeffdaily
> update docker version for magma updates

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
To pick up this change from PyTorch CI image.  https://github.com/pytorch/pytorch/pull/60658
> update docker image tag to tip of tree, pick up expecttest change

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Reverts pytorch/ossci-job-dsl#110
> Revert "update docker image tag to latest as of 2020 07 30"

- src/jobs/pytorch.groovy
- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/caffe2/Images.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Signed-off-by: Kyle Chen <kylechen@amd.com>
> Update to ROCm 4.3.1

- src/jobs/pytorch.groovy
- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/caffe2/Images.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Waiting for https://github.com/pytorch/pytorch/pull/69886 to be merged
> Update to ROCm4.5.2 and py3.7 docker tags and CI runs
