- src/jobs/caffe2.groovy
This PR is to avoid the timeout in windows test: 
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.0-cudnn7-windows-build/11547/console
The timeout happened because we start building aten in that test.
> Bump windows build timeout for cuda tests

- src/jobs/pytorch.groovy
This PR is avoiding the windows build timeout in this test: 
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-build/17686/consoleFull
It happened because we start to build caffe2 and aten in that test.
> increase pytorch windows build timeout

- src/jobs/pytorch.groovy
Switches from microsites/pytorch-tutorials back to pytorch/tutorials/rc1 and creates a new branch for testing rc1 builds.
The plan after final merge is to update output to pytorch/tutorials/master.
> Update Pytorch tutorials to build from pytorch/tutorials/rc1

- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Docker images have been updated with dependencies needed for Caffe2 tests in PyTorch. Most of this landed with https://github.com/pietern/pytorch-dockerfiles/pull/26
@yf225 @pjh5
> Update DockerVersion with dependencies for Caffe2 tests in PyTorch

- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Updated magma via commit https://github.com/pietern/pytorch-dockerfiles/commit/a06f8c4020112fdc6c1ac755ce3b475aa8d7fd51
> bump docker version for newer magma

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
281 was used only for Glow, but it missed llvm8 installation.
283 has clang8 + llvm8
https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/283/
cc: @ezyang
> [Docker] Use newer version for Glow

- src/jobs/pytorch_docker.groovy
Adds the docker image pytorch-linux-bionic-clang9-thrift-llvmdev"
to the list of pytorch images.
> Add Ubuntu bionic docker image.

- src/main/groovy/ossci/pytorch/DockerVersion.groovy
The last commit: android gradle  prefetch dependencies for offline build
https://ci.pytorch.org/jenkins/job/pytorch-docker-master/401/
> bump pytorch docker image version to 401

- src/jobs/pytorch.groovy
This reverts commit a0d1fcbe7dd66d6b89cdb21b69685eeed162ad61.
Revert until test2/test3 split is ready in PyTorch.
CC @ezyang @xw285cornell @sunway513
> Revert "set numParallelTests = 3 to create test3 (#65)"

- src/jobs/pytorch.groovy
- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/caffe2/Images.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
This reverts commit d5efdbe887a386a01b5639517950039d337de234.
Not all tests were present on the CI dashboard.  The one visible build job appeared to succeed, but test1 failed to import torch.  Need to revert until post mortem can be completed.
CC @ezyang @xw285cornell @sunway513
> Revert "use circleci rocm images (#67)"

- src/jobs/caffe2.groovy
- src/jobs/pytorch.groovy
- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/caffe2/Images.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
These images are created from the CircleCI scripts and are used for both pytorch and caffe2 builds and tests.
> For ROCm, switch from caffe2 base images to pytorch base images.

- src/jobs/pytorch.groovy
- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/caffe2/Images.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
This reverts commit 648aabb1be9185b47d24d81f08ce760bac88603d.
caffe2 test failures detected with ROCm 3.5.1 image.  Reverting to restore ROCm CI signal until triage is complete.
> Revert "upgrade rocm image to 3.5.1 (#71)"

- src/jobs/pytorch.groovy
- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/caffe2/Images.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
This reverts commit 7f0e30a0b17d5f1c3152c5386aaa0f242b69e425.
> Revert "reland upgrade rocm image to 3.5.1 (#73)"

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
Rebased https://github.com/pytorch/pytorch/pull/47451, which updated the hash once again.
> updating hashes once again

- src/jobs/caffe2.groovy
- src/jobs/pytorch.groovy
- src/main/groovy/ossci/ParametersUtil.groovy
This brings Jenkins in line with CircleCI as a universal indicator that these are CI jobs.
> add IN_CI env var to pytorch and caffe2 jobs

- src/jobs/caffe2.groovy
- src/jobs/pytorch.groovy
- src/main/groovy/ossci/GitUtil.groovy
This ports similar logic from the circleci agents.
Remove all pytorch and caffe2 uses of DockerVersion.version -- defaults now to empty string.
> generate DOCKER_IMAGE_TAG based on git rev-parse

- src/jobs/caffe2.groovy
PyTorch CI already uses the combination of host-copy for building and docker for testing.
> use host-copy for caffe2 workspace

- src/jobs/pytorch.groovy
We tried disabling this job before, but the daily cron job remained.  Let's try keeping the job definition but removing the cron trigger.
> disable caffe2-master-debug daily cron job

- src/jobs/pytorch.groovy
LTS branches do not generally want jenkins jobs running for them
I don't really know how to test this without just deploying it, seeking guidance @ezyang, @jeffdaily, @jithunnair-amd 
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> disable jobs if targeting lts branch

- src/jobs/pytorch.groovy
ERROR: (pytorch.groovy, line 224) No such property: env for class: javaposse.jobdsl.dsl.helpers.step.PhaseContext
> Fix for skipping of LTS branches

- src/jobs/pytorch.groovy
- src/main/groovy/ossci/JobUtil.groovy
Use blackListTargetBranches feature of ghprb.
CC @jithunnair-amd @seemethere
> Fix for skipping of LTS branches, second attempt.

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
ROCm CI was failing to pull prior image because it was missing.
> update docker image tag to latest as of 2020 07 30

- src/main/groovy/ossci/caffe2/DockerVersion.groovy
- src/main/groovy/ossci/pytorch/DockerVersion.groovy
New tag comes from https://github.com/pytorch/pytorch/pull/67225.
> update docker image tag to pick up new magma version

- src/jobs/pytorch.groovy
Otherwise, too many concurrent builds will run out of disk on trigger3.
Even though wsCleanup() takes place at start of build, disk will fill.
> wsCleanup() post build for master and pull request triggers

- src/main/groovy/ossci/GitUtil.groovy
'fatal: refusing to merge unrelated histories'
Eg: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-build/14390/console
> Add --allow-unrelated-histories flag to workaround git merge error in nightly CI runs

- src/main/groovy/ossci/GitUtil.groovy
Reverts pytorch/ossci-job-dsl#118
> Revert "Add --allow-unrelated-histories flag to workaround git merge error in nightly CI runs"

- src/main/groovy/ossci/GitUtil.groovy
Hopefully this fixes the out of disk issues on trigger.
> forcibly remove .git directory after properties are saved
